/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Code.FormatString;
import Code.PassengerFunction;
import Code.TableFunction;
import datvexe.DatVeXe;
import datvexe.Home;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class pnPassengerManager extends javax.swing.JPanel {

    /**
     * Creates new form pnPassengerManager
     */
    public pnPassengerManager() {
        initComponents();
        
        Start();
        //Load database to table passenger manager
        tbFunction.LoadData(tbPassengerManager, sqlLoadData);
    }
    
    private void Start() {
        btSave.setVisible(false);
        btESC.setVisible(false);
        lbErrorAccout.setVisible(false);
        lbErrorEmail.setVisible(false);
        lbErrorFirstName.setVisible(false);
        lbErrorLastName.setVisible(false);;
        lbErrorNumber.setVisible(false);
        lbErrorPassword.setVisible(false);
        lbPassword.setVisible(false);
        pPassword.setVisible(false);
        pPassword.setEchoChar('\u25cf');
        btPassword.setVisible(false);
    }
    
    public enum Function {
        None,
        Add,
        Delete,
        Edit,
    }
    
    Function userFunction;
    
    //To handle Table
    TableFunction tbFunction = new TableFunction();
    String sqlLoadData = "SELECT * FROM Passenger";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spPassengerManager = new javax.swing.JScrollPane();
        tbPassengerManager = new javax.swing.JTable();
        pFunction = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tLastName = new javax.swing.JTextField();
        tFirstName = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tCellPhone = new javax.swing.JTextField();
        tAccount = new javax.swing.JTextField();
        btAddAcount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btSetting = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        btESC = new javax.swing.JButton();
        lbErrorFirstName = new javax.swing.JLabel();
        lbErrorLastName = new javax.swing.JLabel();
        lbErrorEmail = new javax.swing.JLabel();
        lbErrorAccout = new javax.swing.JLabel();
        lbErrorNumber = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbErrorPassword = new javax.swing.JLabel();
        pPassword = new javax.swing.JPasswordField();
        btPassword = new javax.swing.JButton();
        tSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        tbPassengerManager.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbPassengerManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số điện thoại", "Họ", "Tên", "Email", "Tài khoản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPassengerManager.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbPassengerManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPassengerManagerMouseClicked(evt);
            }
        });
        spPassengerManager.setViewportView(tbPassengerManager);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Số điện thoại*");

        tLastName.setEditable(false);

        tFirstName.setEditable(false);
        tFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFirstNameActionPerformed(evt);
            }
        });

        tEmail.setEditable(false);
        tEmail.setToolTipText("á232");
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });

        tCellPhone.setEditable(false);

        tAccount.setEditable(false);

        btAddAcount.setBackground(new java.awt.Color(0, 102, 204));
        btAddAcount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAddAcount.setForeground(new java.awt.Color(255, 255, 255));
        btAddAcount.setText("Thêm tài khoản");
        btAddAcount.setBorderPainted(false);
        btAddAcount.setEnabled(false);
        btAddAcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAcountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Tài khoản *");

        btSetting.setBackground(new java.awt.Color(0, 102, 204));
        btSetting.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSetting.setForeground(new java.awt.Color(255, 255, 255));
        btSetting.setText("Sửa");
        btSetting.setBorderPainted(false);
        btSetting.setEnabled(false);
        btSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Họ*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Tên*");

        btSave.setBackground(new java.awt.Color(0, 102, 204));
        btSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("Lưu");
        btSave.setBorderPainted(false);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btESC.setBackground(new java.awt.Color(0, 102, 204));
        btESC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btESC.setForeground(new java.awt.Color(255, 255, 255));
        btESC.setText("Hủy");
        btESC.setBorderPainted(false);
        btESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btESCActionPerformed(evt);
            }
        });

        lbErrorFirstName.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorFirstName.setText("Tên không được bỏ trống");

        lbErrorLastName.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorLastName.setText("Họ không được bỏ trống");

        lbErrorEmail.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorEmail.setText("Email không hợp lệ");

        lbErrorAccout.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorAccout.setText("Tài khoản không hợp lệ");

        lbErrorNumber.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorNumber.setText("Số điện thoại không được bỏ trống");

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(0, 102, 204));
        lbPassword.setText("Mật khẩu*");

        lbErrorPassword.setForeground(new java.awt.Color(255, 0, 51));
        lbErrorPassword.setText("Mật khẩu không hợp lệ");

        pPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPasswordActionPerformed(evt);
            }
        });

        btPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPassword.setText("Hiện");
        btPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFunctionLayout = new javax.swing.GroupLayout(pFunction);
        pFunction.setLayout(pFunctionLayout);
        pFunctionLayout.setHorizontalGroup(
            pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFunctionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFunctionLayout.createSequentialGroup()
                        .addComponent(lbErrorFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbErrorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pFunctionLayout.createSequentialGroup()
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbErrorNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pFunctionLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbErrorAccout)
                    .addComponent(tAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbErrorPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPassword))
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lbPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddAcount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btESC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        pFunctionLayout.setVerticalGroup(
            pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbErrorFirstName)
                    .addComponent(lbErrorLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbErrorAccout))
                    .addGroup(pFunctionLayout.createSequentialGroup()
                        .addComponent(pPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbErrorPassword)
                            .addComponent(btPassword))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSetting)
                    .addComponent(btAddAcount))
                .addGap(18, 18, 18)
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btESC))
                .addGap(142, 142, 142))
        );

        tSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tSearchMouseReleased(evt);
            }
        });
        tSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSearchActionPerformed(evt);
            }
        });
        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSearchKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spPassengerManager, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tSearch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spPassengerManager, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbPassengerManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPassengerManagerMouseClicked
        if (tbPassengerManager.getSelectionModel().isSelectionEmpty()) return;
        if (!(tbPassengerManager.isEnabled())) return;

        setTextField(tbFunction.selectRow(tbPassengerManager, 0),
            tbFunction.selectRow(tbPassengerManager, 1),
            tbFunction.selectRow(tbPassengerManager, 2),
            tbFunction.selectRow(tbPassengerManager, 3),
            tbFunction.selectRow(tbPassengerManager, 4));

        btSetting.setEnabled(true);
        //btDelete.setEnabled(true);
        if (tAccount.getText().isEmpty()) {
            btAddAcount.setEnabled(true);
        }
        else {
            btAddAcount.setEnabled(false);
        }
    }//GEN-LAST:event_tbPassengerManagerMouseClicked

    private void tFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFirstNameActionPerformed

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void btAddAcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAcountActionPerformed
        userFunction = Function.Add;
        btAddAcount.setEnabled(false);
        btSetting.setEnabled(false);
        
        //Unlock
        tAccount.setEditable(true);
        btSave.setVisible(true);
        btESC.setVisible(true);
        lbPassword.setVisible(true);
        pPassword.setVisible(true);
        btPassword.setVisible(true);
    }//GEN-LAST:event_btAddAcountActionPerformed

    private void btSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingActionPerformed
        btAddAcount.setEnabled(false);
        btSetting.setEnabled(false);
        
        //Only Edit Name and Email
        tFirstName.setEditable(true);
        tLastName.setEditable(true);
        tEmail.setEditable(true);

        btSave.setVisible(true);
        btESC.setVisible(true);

        userFunction = Function.Edit;
    }//GEN-LAST:event_btSettingActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        //Check input
        if (!CheckInput()) return;

        if (userFunction == Function.Add) AddAccount(tAccount.getText(), pPassword.getText(), tCellPhone.getText());
        else if (userFunction == Function.Edit) EditPassenger();

        Reset();
    }//GEN-LAST:event_btSaveActionPerformed

    private void btESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btESCActionPerformed
        Reset();
    }//GEN-LAST:event_btESCActionPerformed

    private void tSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSearchActionPerformed

    private void tSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSearchMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tSearchMouseReleased

    private void tSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyReleased
        // TODO add your handling code here:
        if(!tSearch.getText().isEmpty()){
            tbFunction.Search(tbPassengerManager,tSearch.getText(),-1);
        }
        else tbFunction.Search(tbPassengerManager,"",-1);
    }//GEN-LAST:event_tSearchKeyReleased

    private void btPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasswordActionPerformed
        // TODO add your handling code here:
        if (btPassword.getText().equals("Hiện")) {
            btPassword.setText("Ẩn");
            pPassword.setEchoChar((char)0);
        }
        else  {
            btPassword.setText("Hiện");
            pPassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_btPasswordActionPerformed

    private void pPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPasswordActionPerformed
    
    private void EditPassenger() {
        FormatString format = new FormatString();
        
        String phoneNumber = tCellPhone.getText();
        String firstName = format.FormatName(tFirstName.getText());
        String lastName = format.FormatName(tLastName.getText());
        String email = tEmail.getText();
        
        //confirm
        int choose = JOptionPane.showConfirmDialog(this, "Xác nhận Sửa TT khách hàng", "Thông Báo",0);
        if (choose == JOptionPane.OK_OPTION) {
            PassengerFunction psFunction = new PassengerFunction(phoneNumber);
            psFunction.EditInfor(firstName, lastName, email);
        }
    }
    
    private void Reset() {
        userFunction = Function.None;
        btAddAcount.setEnabled(true);
        btSetting.setEnabled(true);
        
        //reload table
        tbFunction.LoadData(tbPassengerManager, sqlLoadData);
        tAccount.setText("");
        tCellPhone.setText("");
        tEmail.setText("");
        tFirstName.setText("");
        tLastName.setText("");
        pPassword.setText("");
        
        //Lock
        tAccount.setEditable(false);
        btSave.setVisible(false);
        btESC.setVisible(false);
        lbErrorPassword.setVisible(false);
        lbPassword.setVisible(false);
        pPassword.setVisible(false);
        btAddAcount.setEnabled(false);
        //btDelete.setEnabled(false);
        btSetting.setEnabled(false);
        btPassword.setVisible(false);
        
        lbErrorAccout.setVisible(false);
        lbErrorEmail.setVisible(false);
        lbErrorFirstName.setVisible(false);
        lbErrorLastName.setVisible(false);
        lbErrorNumber.setVisible(false);
        lbErrorPassword.setVisible(false);
    }
    
    private Boolean CheckInput() {
        //check add account
        if (userFunction == Function.Add) {
            if(tAccount.getText().isEmpty()) {
                lbErrorAccout.setVisible(true);
                return false;
            } 
            else lbErrorAccout.setVisible(false);
            
            if (pPassword.getText().isEmpty()) {
                lbErrorPassword.setVisible(true);
                return false;
            }
            else {
                lbErrorPassword.setVisible(false);
                pPassword.setVisible(false);
                lbPassword.setVisible(false);
            }
            return true;
        }
        //check edit
        else if (userFunction == Function.Edit) {
            if(tFirstName.getText().isEmpty()) {
                lbErrorFirstName.setVisible(true);
                return false;
            } 
            else lbErrorFirstName.setVisible(false);
            
            if(tLastName.getText().isEmpty()) {
                lbErrorLastName.setVisible(true);
                return false;
            } 
            else lbErrorLastName.setVisible(false);
            
            if(tCellPhone.getText().isEmpty()) {
                lbErrorNumber.setVisible(true);
                return false;
            } 
            else lbErrorNumber.setVisible(false);
            
            return true;
        }
        
        return true;
    }
    
    private void AddAccount(String account, String password, String number) {
        Connection conn = DatVeXe.layKetNoi();
        //check null
        String sql = "SELECT * FROM ACCOUNT WHERE ACCOUNT = '" + account + "'";
        //add an account
        String sql2 = "INSERT INTO ACCOUNT VALUES (?,?,?) ";
        //add an account into passenger
        String sql3 = "UPDATE PASSENGER SET ACCOUNT = ? WHERE PASSENGER_SDT = '" + number + "'";
        try {
            //active sql
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs =ps.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
                rs.close();
                ps.close();
                conn.close();
                return;
            }
            
            //active sql2
            ps = conn.prepareStatement(sql2);
            ps.setString(1, account);
            ps.setString(2, password);
            ps.setString(3, "passenger");
            ps.executeUpdate();
            
            //active sql3
            ps = conn.prepareStatement(sql3);
            ps.setString(1, account);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công");
            
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }
    
    private void setTextField(String cellPhone, String firstName, String lastName, String email, String account) {
        tCellPhone.setText(cellPhone);
        tFirstName.setText(firstName);
        tLastName.setText(lastName);
        tEmail.setText(email);
        tAccount.setText(account);
   }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAcount;
    private javax.swing.JButton btESC;
    private javax.swing.JButton btPassword;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbErrorAccout;
    private javax.swing.JLabel lbErrorEmail;
    private javax.swing.JLabel lbErrorFirstName;
    private javax.swing.JLabel lbErrorLastName;
    private javax.swing.JLabel lbErrorNumber;
    private javax.swing.JLabel lbErrorPassword;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPanel pFunction;
    private javax.swing.JPasswordField pPassword;
    private javax.swing.JScrollPane spPassengerManager;
    private javax.swing.JTextField tAccount;
    private javax.swing.JTextField tCellPhone;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTable tbPassengerManager;
    // End of variables declaration//GEN-END:variables
}
