/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Code.TableFunction;

/**
 *
 * @author Admin
 */
public class pnScheduelManager extends javax.swing.JPanel {
    private String kind;
    
    //To handle Table
    TableFunction tbFunction = new TableFunction();
    String sqlLoadData = "{call SP_LOAD_TABLE}";
    
    /**
     * Creates new form pnScheduelManager
     */
    public pnScheduelManager(String kind) {
        this.kind = kind;
        initComponents();
        Start();
    }
    
    private void Start() {
        if (kind.equals("gara")) btAddScheduel.setVisible(true);
        else btAddScheduel.setVisible(false);
        
        //Load database to table passenger manager
        tbFunction.LoadData(tbScheduelManager, sqlLoadData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spScheduelManager = new javax.swing.JScrollPane();
        tbScheduelManager = new javax.swing.JTable();
        btAddScheduel = new javax.swing.JButton();

        tbScheduelManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhà xe", "Điểm đi", "Điểm đến", "Thứ", "Thời gian", "Giá vé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spScheduelManager.setViewportView(tbScheduelManager);

        btAddScheduel.setText("Thêm chuyến xe");
        btAddScheduel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddScheduelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spScheduelManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(btAddScheduel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spScheduelManager, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAddScheduel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 371, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddScheduelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddScheduelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddScheduelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddScheduel;
    private javax.swing.JScrollPane spScheduelManager;
    private javax.swing.JTable tbScheduelManager;
    // End of variables declaration//GEN-END:variables
}
