/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author huynh
 */
public class AddNewEmployer extends javax.swing.JDialog {

    /**
     * Creates new form AddNewEmployer
     */
    
    public AddNewEmployer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lbErrAcc.setVisible(false);
        lbErrCMND.setVisible(false);
        lbErrPhone.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        cbKind = new javax.swing.JComboBox<>();
        txCMND = new javax.swing.JTextField();
        txLastName = new javax.swing.JTextField();
        lbErrAcc = new javax.swing.JLabel();
        txPhone = new javax.swing.JTextField();
        lbErrCMND = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txFirstname = new javax.swing.JTextField();
        lbErrPhone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txAccount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btAddEmployer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Tên đăng nhập");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(790, 260, 170, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Vai trò nhân viên");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(790, 440, 140, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Mật khẩu");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(790, 350, 110, 20);

        btExit.setBackground(new java.awt.Color(0, 0, 255));
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("Quay lại");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jPanel1.add(btExit);
        btExit.setBounds(983, 90, 160, 23);

        cbKind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbKind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lí", "Nhân viên" }));
        jPanel1.add(cbKind);
        cbKind.setBounds(790, 470, 190, 30);

        txCMND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txCMND);
        txCMND.setBounds(160, 370, 220, 30);

        txLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txLastName);
        txLastName.setBounds(420, 290, 240, 30);

        lbErrAcc.setForeground(new java.awt.Color(255, 51, 51));
        lbErrAcc.setText("Tên đăng nhập đã tồn tại");
        jPanel1.add(lbErrAcc);
        lbErrAcc.setBounds(790, 330, 187, 14);

        txPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txPhone);
        txPhone.setBounds(420, 370, 240, 30);

        lbErrCMND.setForeground(new java.awt.Color(255, 51, 51));
        lbErrCMND.setText("CMND đã được đăng kí trước đó");
        jPanel1.add(lbErrCMND);
        lbErrCMND.setBounds(160, 410, 187, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THÔNG TIN NHÂN VIÊN MỚI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 200, 380, 40);

        txFirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txFirstname);
        txFirstname.setBounds(160, 290, 220, 30);

        lbErrPhone.setForeground(new java.awt.Color(255, 51, 51));
        lbErrPhone.setText("SĐT đã được đăng kí trước đó");
        jPanel1.add(lbErrPhone);
        lbErrPhone.setBounds(420, 410, 187, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CMND/Căn Cước Công Dân");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 340, 230, 20);

        txAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txAccount);
        txAccount.setBounds(790, 290, 330, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Họ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 260, 70, 20);

        txPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txPassword);
        txPassword.setBounds(790, 380, 330, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Tên");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 260, 80, 17);

        buttonGroup1.add(rdMale);
        rdMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdMale.setText("Nam");
        jPanel1.add(rdMale);
        rdMale.setBounds(160, 470, 93, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("SĐT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 340, 70, 14);

        buttonGroup1.add(rdFemale);
        rdFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdFemale.setText("Nữ");
        jPanel1.add(rdFemale);
        rdFemale.setBounds(300, 470, 93, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Giới tính");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 440, 110, 17);

        btAddEmployer.setBackground(new java.awt.Color(27, 102, 177));
        btAddEmployer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAddEmployer.setForeground(new java.awt.Color(255, 255, 255));
        btAddEmployer.setText("+ Thêm nhân viên");
        btAddEmployer.setBorderPainted(false);
        btAddEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddEmployerActionPerformed(evt);
            }
        });
        jPanel1.add(btAddEmployer);
        btAddEmployer.setBounds(400, 580, 530, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("THÔNG TIN TÀI KHOẢN");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(750, 220, 200, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/iconTong.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 20, 160, 123);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/BackGround.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 4, 1280, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddEmployerActionPerformed
       DatVeXe datvexe = new DatVeXe();
        Connection conn = datvexe.layKetNoi();
        String sql = "INSERT INTO Staff VALUES(?,?,?,?,?,?,?)";
        String cmnd = txCMND.getText().trim(); 
        String firstName= txFirstname.getText().trim();
        String lastname = txLastName.getText().trim();
        String phone = txPhone.getText().trim();
        String sex = "";
        if(rdMale.isSelected()){
            sex = "Nam";
        }else{
            sex = "Nữ";
        }
        String account = txAccount.getText().trim();
        String password = txPassword.getText().trim();
        
        if(cmnd.trim().equals("") || firstName.trim().equals("") || lastname.trim().equals("") || phone.trim().equals("") || account.trim().equals("") || password.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Các trường thông tin không được để trống!");
            return; 
        }
        String phonePattern = "0[0-9]{9}";
       if(phone.length()!=10 || phone.matches(phonePattern)==false){
           JOptionPane.showMessageDialog(rootPane, "Số điện thoại sai định dạng");
            return; 
       }
        String cmndPattern = "[0-9]{10}";
       if(cmnd.length()!=10 || cmnd.matches(cmndPattern)==false){
           JOptionPane.showMessageDialog(rootPane, "Chứng minh nhân dân sai định dạng");
            return; 
       }
       
        
        String sql2 = "INSERT INTO Account VALUES(?,?,?)"; 
        String kind; 
        if(cbKind.getSelectedIndex()==0){
            kind = "boss";
        }else if(cbKind.getSelectedIndex()==1){
            kind = "staff";
        }else{
            kind = "gara";
        }
        
        PreparedStatement pstt2; 
        
        try {
            int checkAccount = findAccount(account, conn);
            if(checkAccount==-1){
                lbErrAcc.setVisible(true);
                return; 
            }
            pstt2 = conn.prepareStatement(sql2);
            pstt2.setString(1, account);
            pstt2.setString(2, password);
            pstt2.setString(3, kind);
            
            pstt2.executeUpdate(); 
            
        } catch (SQLException ex) {
            Logger.getLogger(AddNewEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        PreparedStatement pstt;
        try {
            int checkCMND = findCMND(cmnd, conn);
            if(checkCMND==-1){
            lbErrCMND.setVisible(true);
            return; 
            }
            int checkPhone = findPhone(phone, conn);
            if(checkPhone ==-1){
                lbErrPhone.setVisible(true);
                return; 
            }
            pstt = conn.prepareStatement(sql);
            pstt.setString(1, cmnd);
            pstt.setString(2, firstName);
            pstt.setString(3, lastname);
            pstt.setString(4, phone);
            pstt.setString(5, sex);
            pstt.setString(6, account);
            pstt.setBoolean(7, true);
            int x = pstt.executeUpdate();
            if(x>0){
                JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công!");
                this.dispose();
                ManageStaff mnStaff = new ManageStaff();
                mnStaff.setLocationRelativeTo(null);
                mnStaff.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddNewEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btAddEmployerActionPerformed

    private void txLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLastNameActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        this.dispose();
        
        ManageStaff manageStaff = new ManageStaff();
        manageStaff.setLocationRelativeTo(null);
        manageStaff.setVisible(true);
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewEmployer dialog = new AddNewEmployer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public int findAccount(String account, Connection conn){
    
    String sql = "select * from account where account = ?"; 
    PreparedStatement pstt;
        try {
            pstt = conn.prepareStatement(sql);
            pstt.setString(1, account);
            ResultSet rs = pstt.executeQuery();
            if(rs.next()){
                return -1; 
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(AddNewEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 1;
    }
    public int findPhone(String phone, Connection conn){
    
    String sql = "select * from Staff where Staff_SDT = ?"; 
    PreparedStatement pstt;
        try {
            pstt = conn.prepareStatement(sql);
            pstt.setString(1, phone);
            ResultSet rs = pstt.executeQuery();
            if(rs.next()){
                return -1; 
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(AddNewEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 1;
    }
    public int findCMND(String cmnd, Connection conn){
    
    String sql = "select * from Staff where Staff_CMND = ?"; 
    PreparedStatement pstt;
        try {
            pstt = conn.prepareStatement(sql);
            pstt.setString(1, cmnd);
            ResultSet rs = pstt.executeQuery();
            if(rs.next()){
                return -1; 
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(AddNewEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 1;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddEmployer;
    private javax.swing.JButton btExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbErrAcc;
    private javax.swing.JLabel lbErrCMND;
    private javax.swing.JLabel lbErrPhone;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextField txAccount;
    private javax.swing.JTextField txCMND;
    private javax.swing.JTextField txFirstname;
    private javax.swing.JTextField txLastName;
    private javax.swing.JTextField txPassword;
    private javax.swing.JTextField txPhone;
    // End of variables declaration//GEN-END:variables
}
