/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author huynh
 */
public class AddNewGara extends javax.swing.JDialog {

    /**
     * Creates new form AddNewGara
     */
    
    //check infor: 
    int empty = -1; 
    int duplicateGaraName = -2;
    int duplicateAccount = -3; 
    int duplicateBusResNum = -4; 
    int emptyPicture = -5; 
    public AddNewGara(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    String saveFolder = System.getProperty("user.dir")+"\\galaryPicture\\";
    String nameofPicture ="";
    File file; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btAddGara = new javax.swing.JButton();
        txGaraName = new javax.swing.JTextField();
        txGaraReview = new javax.swing.JTextField();
        txBusResNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txAccount = new javax.swing.JTextField();
        txPassword = new javax.swing.JTextField();
        btPickPicture = new javax.swing.JButton();
        lbPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên nhà xe");

        jLabel2.setText("Hình ảnh");

        jLabel3.setText("Đánh giá");

        jLabel4.setText("Giấy phép đăng kí kinh doanh");

        btAddGara.setText("Thêm nhà xe");
        btAddGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddGaraActionPerformed(evt);
            }
        });

        jLabel5.setText("Tên đăng nhập");

        jLabel6.setText("Mật khẩu");

        btPickPicture.setText("Chọn ảnh...");
        btPickPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPickPictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btAddGara, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txGaraName)
                        .addComponent(txGaraReview)
                        .addComponent(txBusResNum, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(txAccount)
                        .addComponent(txPassword))
                    .addComponent(btPickPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(lbPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txGaraName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btPickPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txGaraReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txBusResNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAddGara, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddGaraActionPerformed
        String garaName = txGaraName.getText().trim(); 
        String garaReview = txGaraReview.getText().trim();
        String BusResNum = txBusResNum.getText().trim(); 
        String account = txAccount.getText().trim();
        String password = txPassword.getText().trim();
        
        
        DatVeXe datvexe = new DatVeXe();
        Connection conn = datvexe.layKetNoi();
        
        int checkResult = checkInfor(garaName, garaReview, BusResNum, account, password, conn);
        if(checkResult==empty){
            JOptionPane.showMessageDialog(rootPane, "Thông tin phải được điền đầy đủ");
            return; 
        }
        
        
        else  if(checkResult==duplicateGaraName){
            JOptionPane.showMessageDialog(rootPane, "Tên nhà xe đã có trong hệ thống \nVui lòng chọn tên nhà xe khác!");
            return; 
        }
        
        
        
        else  if(checkResult==duplicateAccount){
            JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập đã có trong hệ thống \nVui lòng chọn tên đăng nhập khác!");
            return; 
                }
        
        
        
        else if(checkResult==duplicateBusResNum){
            JOptionPane.showMessageDialog(rootPane, "Giấy phép ĐKKD đã có trong hệ thống \nVui lòng kiểm tra lại!");
            return; 
        }else if(checkResult==emptyPicture){
            JOptionPane.showMessageDialog(rootPane, "Hình ảnh nhà xe không được để trống");
            return; 
        }
        
        String sql = "INSERT INTO ACCOUNT values(?,?,?)";
                PreparedStatement pstt;
                try {
                    pstt = conn.prepareStatement(sql);
                    pstt.setString(1, account);
                    pstt.setString(2, password);
                    pstt.setString(3, "Gara");
                    int x = pstt.executeUpdate();
                    if(x>0){
                        
                    }
                 
                } catch (SQLException ex) {
                    Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
        
        
        String sql2 = "INSERT INTO Gara VALUES(?,?,?,?,?,?)";
        
        PreparedStatement pstt2;
        try {
            
            pstt2 = conn.prepareStatement(sql2);
            pstt2.setString(1, garaName);
            pstt2.setString(2, nameofPicture);
            pstt2.setString(3, garaReview);
            pstt2.setString(4, BusResNum);
            pstt2.setBoolean(5,true);
            pstt2.setString(6,account);
            int x = pstt2.executeUpdate();
            if(x>0){
                JOptionPane.showMessageDialog(rootPane, "Thêm nhà xe thành công!");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Có lỗi xảy ra!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddNewEmployer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //save file ra thu muc galaryPicture: 
            //luu file anh ra vung nho
            BufferedImage bImage = null;
            try {

                bImage = ImageIO.read(file);
                ImageIO.write(bImage, "jpg", new File(saveFolder+nameofPicture));
                ImageIO.write(bImage, "png", new File(saveFolder+nameofPicture));
                ImageIO.write(bImage, "jpeg", new File(saveFolder+nameofPicture));
 
         } catch (IOException e) {
               System.out.println("Exception occured :" + e.getMessage());
         }
         System.out.println("Images were written succesfully.");
    }//GEN-LAST:event_btAddGaraActionPerformed

    private void btPickPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPickPictureActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Hình ảnh", "jpg","jpeg","png");
        fileChooser.setFileFilter(extension);
        fileChooser.setMultiSelectionEnabled(false);
        
        int x = fileChooser.showDialog(this, "Chọn ảnh nhà xe");
        if(x==JFileChooser.APPROVE_OPTION){
            file = fileChooser.getSelectedFile();
            ImageIcon icon  = new ImageIcon(file.getAbsolutePath());
            Image image = icon.getImage();
            Image newImage = image.getScaledInstance(410,410, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(newImage);
            lbPicture.setIcon(icon);
          //lay ten file
          System.out.println(file.getAbsolutePath());
                
            String finalString = file.getAbsolutePath();
            char s = '\\';
            String result="";
            for(int i =finalString.length()-1;i>=0;i--){
                char compareStr = finalString.charAt(i);
                if(Character.compare(s, compareStr)==0){
                    result = finalString.substring(i+1);
                    break;
                }
            }
            nameofPicture = result; 
            System.out.println("ten cua anh: "+nameofPicture);
            
            
        }
    }//GEN-LAST:event_btPickPictureActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewGara dialog = new AddNewGara(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public int checkInfor(String garaName, String garaReview, String busResNum, String account, String password, Connection conn){
        
        
        if(garaName.trim().equals("")|| garaReview.trim().equals("")|| busResNum.trim().equals("")|| account.trim().equals("")||password.trim().equals("")){
            return -1; 
        }
        
        if(nameofPicture.equals("")) return -5; 
        String sql = "select * from Gara where Gara_Name=?";
        try {
            PreparedStatement pstt = conn.prepareStatement(sql);
            pstt.setString(1, garaName);
            ResultSet rs = pstt.executeQuery(); 
            if(rs.next()){
                return -2; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
           String sql2 = "select * from account where account.account = ?";
        try {
            
            PreparedStatement pstt2 = conn.prepareStatement(sql2);
            pstt2.setString(1, account);
            ResultSet rs = pstt2.executeQuery(); 
            if(rs.next()){
                System.out.println("thong tin bi trung roi ne!");
                return -3; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        
            String sql3 = "select Bus_Res_number from Gara where Bus_Res_number=?";
        try {
            PreparedStatement pstt3 = conn.prepareStatement(sql3);
            pstt3.setString(1, busResNum);
            ResultSet rs = pstt3.executeQuery(); 
            if(rs.next()){
                return -4; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        return 0;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddGara;
    private javax.swing.JButton btPickPicture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbPicture;
    private javax.swing.JTextField txAccount;
    private javax.swing.JTextField txBusResNum;
    private javax.swing.JTextField txGaraName;
    private javax.swing.JTextField txGaraReview;
    private javax.swing.JTextField txPassword;
    // End of variables declaration//GEN-END:variables
}
