
package datvexe;

import Panel.pnPassengerManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Code.TableFunction;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Code.FormatString;
import Code.PassengerFunction;
import javax.swing.JPanel;
import Panel.pnScheduelManager;
/**
 *
 * @author Vanic
 */

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */

    public enum Function {
        None,
        Add,
        Delete,
        Edit,
    }
    
    Function userFunction;
    
    String kind = ""; // loại người dùng (staff,boss,gara)
    String user = ""; // tên đăng nhập của người dùng

    //To handle Table
    TableFunction tbFunction = new TableFunction();
    String sqlLoadData = "SELECT * FROM Passenger";
    

    public Home(String user, String kind) {
        initComponents();
        
        this.kind = kind;
        if(this.kind.equals("staff")){
            btManageStaff.setVisible(false);
            btManageGara.setVisible(false);
            btInventor.setVisible(false);
        }else if (this.kind.equals("gara")){
            btManageStaff.setVisible(false);
            btManageGara.setVisible(false);
            btInventor.setVisible(false);
            btn_managerTicket.setVisible(false);
        }
        label_staffName.setText(getNameStaff(user)+" ("+kind+")");
        this.user = user;
        
        Start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label_staffName = new javax.swing.JLabel();
        btn_infoStaff = new javax.swing.JButton();
        btInventor = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btManageStaff = new javax.swing.JButton();
        btManageGara = new javax.swing.JButton();
        btn_managerTicket = new javax.swing.JButton();
        tpManger = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("Thêm tài khoản");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        label_staffName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_staffName.setForeground(new java.awt.Color(255, 0, 0));
        label_staffName.setText("jLabel1");
        jPanel1.add(label_staffName);
        label_staffName.setBounds(160, 34, 300, 40);

        btn_infoStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/ThongTinCaNhanIcon.png"))); // NOI18N
        btn_infoStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoStaffActionPerformed(evt);
            }
        });
        jPanel1.add(btn_infoStaff);
        btn_infoStaff.setBounds(220, 120, 160, 200);

        btInventor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/ThongKeDoanhThuIcon.png"))); // NOI18N
        btInventor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInventorActionPerformed(evt);
            }
        });
        jPanel1.add(btInventor);
        btInventor.setBounds(980, 120, 160, 200);

        btn_logout.setBackground(new java.awt.Color(27, 102, 177));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Đăng xuất");
        btn_logout.setBorderPainted(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(160, 80, 150, 25);

        btManageStaff.setBackground(new java.awt.Color(27, 102, 177));
        btManageStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btManageStaff.setForeground(new java.awt.Color(255, 255, 255));
        btManageStaff.setText("Quản lí nhân viên");
        btManageStaff.setBorderPainted(false);
        btManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageStaffActionPerformed(evt);
            }
        });
        jPanel1.add(btManageStaff);
        btManageStaff.setBounds(860, 40, 350, 40);

        btManageGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/QuanLiNhaXeIcon.png"))); // NOI18N
        btManageGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageGaraActionPerformed(evt);
            }
        });
        jPanel1.add(btManageGara);
        btManageGara.setBounds(730, 120, 157, 200);

        btn_managerTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/QuanLiVeIcon.png"))); // NOI18N
        btn_managerTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_managerTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btn_managerTicket);
        btn_managerTicket.setBounds(470, 120, 160, 200);
        jPanel1.add(tpManger);
        tpManger.setBounds(40, 330, 1190, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/IconNhanVien.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 20, 83, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/BackGround.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AddPanel(JPanel pn, String heading) {
        tpManger.add(heading, pn);
    }
    
    private void Start() {
        if (kind.equals("staff") || kind.equals("boss")) {
            pnPassengerManager pn = new pnPassengerManager();
            AddPanel(pn, "Quản lý khách hàng");
            
            pnScheduelManager pn2 = new pnScheduelManager(this.kind, this.user);
            AddPanel(pn2, "Quản lý chuyến xe");
        }
        else if (kind.equals("gara")) {
            pnScheduelManager pn2 = new pnScheduelManager(this.kind, this.user);
            AddPanel(pn2, "Quản lý chuyến xe");
        }
    }
    
    //hàm lấy thông tin của nhân viên đã đăng nhập vào trang chủ
    public String getNameStaff(String userName){
        String name = "";
        Connection ketNoi = DatVeXe.layKetNoi();
        String sql = "select Staff_First_Name, Staff_Last_Name from Staff where Staff_Account = '"+userName+"'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                name = rs.getString("Staff_First_Name")+" "+rs.getString("Staff_Last_Name");
            }
            
        } catch (Exception e) {
            System.out.println("Loi getNameStaff"+ e);
        }
        return name;
    }
    private void btn_infoStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoStaffActionPerformed
        infoStaff info = new infoStaff(user);
        info.setLocationRelativeTo(null);
        info.setVisible(true);
    }//GEN-LAST:event_btn_infoStaffActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.setVisible(false);
        Login lg = new Login();
        lg.setLocationRelativeTo(null);
        lg.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageStaffActionPerformed
//        this.setVisible(false);
        ManageStaff manageStaff = new ManageStaff();
        manageStaff.setLocationRelativeTo(null);
        manageStaff.setVisible(true);
    }//GEN-LAST:event_btManageStaffActionPerformed


    private void btn_managerTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_managerTicketActionPerformed

        ManageTicket mt = new ManageTicket();
        mt.setLocationRelativeTo(null);
        mt.setVisible(true);
    }//GEN-LAST:event_btn_managerTicketActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
        
    private void btManageGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageGaraActionPerformed
        ManageGara manageGara = new ManageGara();
        manageGara.setLocationRelativeTo(null);
        manageGara.setVisible(true);
    }//GEN-LAST:event_btManageGaraActionPerformed

    private void btInventorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInventorActionPerformed
        InventoryProfit inventoryProfit = new InventoryProfit();
        inventoryProfit.setLocationRelativeTo(null);
        inventoryProfit.setVisible(true);
    }//GEN-LAST:event_btInventorActionPerformed
    
//    private void EditPassenger() {
//        FormatString format = new FormatString();
//        
//        String phoneNumber = tCellPhone.getText();
//        String firstName = format.FormatName(tFirstName.getText());
//        String lastName = format.FormatName(tLastName.getText());
//        String email = tEmail.getText();
//        
//        //confirm
//        int choose = JOptionPane.showConfirmDialog(this, "Xác nhận Sửa TT khách hàng", "Thông Báo",0);
//        if (choose == JOptionPane.OK_OPTION) {
//            PassengerFunction psFunction = new PassengerFunction(phoneNumber);
//            psFunction.EditInfor(firstName, lastName, email);
//        }
//    }
//    
//    private void Reset() {
//        userFunction = Function.None;
//
//        //reload table
//        tbFunction.LoadData(tbPassengerManager, sqlLoadData);
//        tAccount.setText("");
//        tCellPhone.setText("");
//        tEmail.setText("");
//        tFirstName.setText("");
//        tLastName.setText("");
//        tPassword.setText("");
//        
//        //Lock
//        tAccount.setEditable(false);
//        btSave.setVisible(false);
//        btESC.setVisible(false);
//        lbErrorPassword.setVisible(false);
//        lbPassword.setVisible(false);
//        tPassword.setVisible(false);
//        btAddAcount.setEnabled(false);
//        btDelete.setEnabled(false);
//        btSetting.setEnabled(false);
//    }
//    
//    private Boolean CheckInput() {
//        //check add account
//        if (userFunction == Function.Add) {
//            if(tAccount.getText().isEmpty()) {
//                lbErrorAccout.setVisible(true);
//                return false;
//            } 
//            else lbErrorAccout.setVisible(false);
//            
//            if (tPassword.getText().isEmpty()) {
//                lbErrorPassword.setVisible(true);
//                return false;
//            }
//            else {
//                lbErrorPassword.setVisible(false);
//                tPassword.setVisible(false);
//                lbPassword.setVisible(false);
//            }
//            return true;
//        }
//        //check edit
//        else if (userFunction == Function.Edit) {
//            if(tFirstName.getText().isEmpty()) {
//                lbErrorFirstName.setVisible(true);
//                return false;
//            } 
//            else lbErrorFirstName.setVisible(false);
//            
//            if(tLastName.getText().isEmpty()) {
//                lbErrorLastName.setVisible(true);
//                return false;
//            } 
//            else lbErrorLastName.setVisible(false);
//            
//            if(tCellPhone.getText().isEmpty()) {
//                lbErrorNumber.setVisible(true);
//                return false;
//            } 
//            else lbErrorNumber.setVisible(false);
//            
//            return true;
//        }
//        
//        return true;
//    }
//    
//    private void AddAccount(String account, String password, String number) {
//        Connection conn = DatVeXe.layKetNoi();
//        //check null
//        String sql = "SELECT * FROM ACCOUNT WHERE ACCOUNT = '" + account + "'";
//        //add an account
//        String sql2 = "INSERT INTO ACCOUNT VALUES (?,?,?) ";
//        //add an account into passenger
//        String sql3 = "UPDATE PASSENGER SET ACCOUNT = ? WHERE PASSENGER_SDT = '" + number + "'";
//        try {
//            //active sql
//            PreparedStatement ps = conn.prepareStatement(sql);
//            ResultSet rs =ps.executeQuery();
//            
//            if(rs.next()){
//                JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
//                rs.close();
//                ps.close();
//                conn.close();
//                return;
//            }
//            
//            //active sql2
//            ps = conn.prepareStatement(sql2);
//            ps.setString(1, account);
//            ps.setString(2, password);
//            ps.setString(3, "passenger");
//            ps.executeUpdate();
//            
//            //active sql3
//            ps = conn.prepareStatement(sql3);
//            ps.setString(1, account);
//            ps.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công");
//            
//            rs.close();
//            ps.close();
//            conn.close();
//        } catch (Exception e) {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, e);
//        }
//        
//    }
//    
//    private void setTextField(String cellPhone, String firstName, String lastName, String email, String account) {
//        tCellPhone.setText(cellPhone);
//        tFirstName.setText(firstName);
//        tLastName.setText(lastName);
//        tEmail.setText(email);
//        tAccount.setText(account);
//   }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home("","none").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInventor;
    private javax.swing.JButton btManageGara;
    private javax.swing.JButton btManageStaff;
    private javax.swing.JButton btn_infoStaff;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_managerTicket;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_staffName;
    private javax.swing.JTabbedPane tpManger;
    // End of variables declaration//GEN-END:variables
}
