/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanic
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        label_err1 = new javax.swing.JLabel();
        label_err2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_user.setCaretColor(new java.awt.Color(255, 0, 0));
        jPanel1.add(txt_user);
        txt_user.setBounds(630, 200, 300, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tên đăng nhập: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(630, 170, 130, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Mật khẩu: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 290, 90, 20);

        btn_login.setBackground(new java.awt.Color(27, 102, 177));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Đăng nhập");
        btn_login.setBorderPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login);
        btn_login.setBounds(631, 410, 300, 60);

        label_err1.setText("jLabel3");
        jPanel1.add(label_err1);
        label_err1.setBounds(630, 240, 300, 14);

        label_err2.setText("jLabel4");
        jPanel1.add(label_err2);
        label_err2.setBounds(630, 360, 300, 14);
        jPanel1.add(txt_password);
        txt_password.setBounds(630, 320, 300, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 102, 177));
        jLabel4.setText("THÔNG TIN ĐĂNG NHẬP");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(630, 80, 300, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/DangNhap_BG.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-6, -6, 1040, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clear(){
        txt_password.setText("");
        txt_user.setText("");
        label_err1.setText("");
        label_err2.setText("");
    }
    public String checkAccount(String user, String password){
        String kind = "";
        Connection ketNoi = DatVeXe.layKetNoi();
        String sql = "select Kind from Account where Account = '"+user+"' and Password = '"+password+"'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (!rs.next()) return kind = "none";
            kind = rs.getString("Kind");
        } catch (Exception e) {
            System.out.println("Loi checkAccount! "+ e);
        }
        return kind;
    }
    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String userName = txt_user.getText();
        String password = String.valueOf(txt_password.getPassword());
        if (userName.equals("")){
            label_err1.setForeground(Color.red);
            label_err1.setText("Tên đăng nhập không được bỏ trống!");
        }
        if (password.equals("")){
            label_err2.setForeground(Color.red);
            label_err2.setText("mật khẩu không được bỏ trống!");
        }
        if (!userName.equals("")){
            label_err1.setText("");
        }
        if (!password.equals("")){
            label_err2.setText("");
        }
        
        String kind = "";
        if (userName.compareTo("")!=0 && password.compareTo("")!=0){
           kind = checkAccount(userName, password);
        }
        switch(kind){
            case "staff":
                this.setVisible(false);
                Home home = new Home(userName, kind);
                home.setLocationRelativeTo(null);
                home.setVisible(true);
                break;
             case "boss":
                this.setVisible(false);
                Home home2 = new Home(userName, kind);
                home2.setLocationRelativeTo(null);
                home2.setVisible(true);
                break;
             case "gara":
                 this.setVisible(false);
                Home home3 = new Home(userName, kind);
                home3.setLocationRelativeTo(null);
                home3.setVisible(true);
                break;
            case "none":
                JOptionPane.showMessageDialog(this, "tài khoản không tồn tại hoặc mật khẩu không đúng","Inane Eror",JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_err1;
    private javax.swing.JLabel label_err2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
