/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vanic
 */
public class ManageTicket extends javax.swing.JFrame {

    /**
     * Creates new form ManageTicket
     */
    public ManageTicket() {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getData();     
    }
    public void getData(){
        DefaultTableModel dtm = (DefaultTableModel) table_listTicket.getModel();
        dtm.setNumRows(0);
        Vector vt;
        Connection ketNoi = DatVeXe.layKetNoi();
        String sql = "select * from Ticket";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                vt = new Vector();
                vt.add(rs.getString("Ticket_No"));
                vt.add(rs.getString("Seat_Position"));
                vt.add(rs.getString("Seat_Kind"));
                vt.add(rs.getString("Is_Paid"));
                vt.add(rs.getString("Passenger_Note"));
                vt.add(rs.getString("Book_Time"));
                vt.add(rs.getString("Staff_CMND"));
                vt.add(rs.getString("Passenger_SDT"));
                vt.add(rs.getString("Trip_No"));
                dtm.addRow(vt);
            }
        } catch (Exception e) {
            System.out.println("loi getData"+e);
        }
        table_listTicket.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_listTicket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_cancelTicket = new javax.swing.JButton();
        txt_time = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_noiDi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_orderTicket = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_noiDen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        table_listTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket_No", "Seat_Position", "Seat_Kind", "Is_Paid", "Passenger_Note", "Book_Time", "Staff_CMND", "Passenger_SDT", "Trip_No"
            }
        ));
        jScrollPane1.setViewportView(table_listTicket);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 320, 1240, 370);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("SDT: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 250, 150, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TÌM KIẾM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 250, 120, 40);

        txt_sdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_sdt.setForeground(new java.awt.Color(255, 0, 0));
        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sdt);
        txt_sdt.setBounds(180, 280, 190, 30);

        btn_search.setBackground(new java.awt.Color(27, 102, 177));
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("search");
        btn_search.setBorderPainted(false);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search);
        btn_search.setBounds(1130, 280, 110, 30);

        btn_cancelTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/HuyVeIcon.png"))); // NOI18N
        btn_cancelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelTicket);
        btn_cancelTicket.setBounds(680, 110, 170, 130);

        txt_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_time.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txt_time);
        txt_time.setBounds(880, 280, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Thời Gian đi: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(880, 250, 220, 17);

        txt_noiDi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_noiDi.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txt_noiDi);
        txt_noiDi.setBounds(400, 280, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Nơi Đi: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 250, 200, 17);

        btn_orderTicket.setBackground(new java.awt.Color(255, 255, 255));
        btn_orderTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/DatVeIcon.png"))); // NOI18N
        btn_orderTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_orderTicketActionPerformed(evt);
            }
        });
        jPanel1.add(btn_orderTicket);
        btn_orderTicket.setBounds(400, 110, 170, 130);

        btn_back.setText("<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(10, 10, 41, 23);

        txt_noiDen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_noiDen.setForeground(new java.awt.Color(255, 0, 0));
        txt_noiDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noiDenActionPerformed(evt);
            }
        });
        jPanel1.add(txt_noiDen);
        txt_noiDen.setBounds(640, 280, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Nơi Đến: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(640, 250, 210, 17);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/iconTong.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 20, 160, 123);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/BackGround.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1280, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_orderTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_orderTicketActionPerformed
        this.setVisible(false);
        OrderTicket order = new OrderTicket();
        order.setLocationRelativeTo(null);
        order.setVisible(true);
    }//GEN-LAST:event_btn_orderTicketActionPerformed

    private void btn_cancelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelTicketActionPerformed
        this.setVisible(false);
        InputSDT ip = new InputSDT();
        ip.setLocationRelativeTo(null);
        ip.setVisible(true);
    }//GEN-LAST:event_btn_cancelTicketActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    public void searchListTicketFilter(String sdt, String noiDi, String noiDen, String time){
        DefaultTableModel dtm = (DefaultTableModel) table_listTicket.getModel();
        dtm.setNumRows(0);
        Vector vt;
        String sqlSDT = "t.Passenger_SDT = N'"+sdt+"'";
        String sqlnoiDi = "st.station_Name = N'"+noiDi+"'";
        String sqlnoiDen = "sta.station_Name = N'"+noiDen+"'";
        String sqltime = "CONVERT(VARCHAR(25), t.Book_Time, 126) LIKE '%"+time+"%'";
        
        boolean check = false;
        Connection ketNoi = DatVeXe.layKetNoi();
        String sql = "select Ticket_No,Seat_Position,Seat_Kind,Is_Paid,Passenger_Note, Book_Time, Staff_CMND, Passenger_SDT, t.Trip_No "
                + "from (Ticket t inner join Trip tr on t.Trip_No = tr.Trip_No) "
                + "inner join ScheduleOfGara s on tr.TripOfGara_no = s.TripOfGara_no "
                + "inner join TotalScheduels total on s.Schedule_no = total.SChedule_no "
                + "inner join Station st on total.BeginStation = st.station_No "
                + "inner join Station sta on total.EndStation = sta.station_No ";
        if (!sdt.equals("")){
            if (check == false){
                check = true;
                sql += "where "+sqlSDT;
            }else{
                sql += " and "+sqlSDT;
            }
        }
        if (!noiDi.equals("")){
            if (check == false){
                check = true;
                sql += "where "+sqlnoiDi;
            }else{
                sql += " and "+sqlnoiDi;
            }
        }
        if (!noiDen.equals("")){
            if (check == false){
                check = true;
                sql += "where "+sqlnoiDen;
            }else{
                sql += " and "+sqlnoiDen;
            }
        }
        if (!time.equals("")){
            if (check == false){
                check = true;
                sql += "where "+sqltime;
            }else{
                sql += " and "+sqltime;
            }
        }
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                vt = new Vector();
                vt.add(rs.getString("Ticket_No"));
                vt.add(rs.getString("Seat_Position"));
                vt.add(rs.getString("Seat_Kind"));
                vt.add(rs.getString("Is_Paid"));
                vt.add(rs.getString("Passenger_Note"));
                vt.add(rs.getString("Book_Time"));
                vt.add(rs.getString("Staff_CMND"));
                vt.add(rs.getString("Passenger_SDT"));
                vt.add(rs.getString("Trip_No"));
                dtm.addRow(vt);
            }
        } catch (Exception e) {
            System.out.println("loi getData"+e);
        }
        table_listTicket.setModel(dtm);
    }
   
    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String sdt = txt_sdt.getText();
        String noiDi = txt_noiDi.getText();
        String noiDen = txt_noiDen.getText();
        String time = txt_time.getText();
        searchListTicketFilter(sdt, noiDi, noiDen, time);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_noiDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noiDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noiDenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancelTicket;
    private javax.swing.JButton btn_orderTicket;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_listTicket;
    private javax.swing.JTextField txt_noiDen;
    private javax.swing.JTextField txt_noiDi;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables
}
