/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huynh
 */
public class ShowGaraList extends javax.swing.JFrame {
    DefaultTableModel dtf;
    DatVeXe datvexe = new DatVeXe(); 
        Connection connection = datvexe.layKetNoi();
    
    /**
     * Creates new form ManageGara
     */
    public ShowGaraList() {
        initComponents();
        
        performed(connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListGaras = new javax.swing.JTable();
        btDelGara = new javax.swing.JButton();
        btUpdateGara = new javax.swing.JButton();
        btViewDetail = new javax.swing.JButton();
        ckShowAll = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txgaraName = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("DANH SÁCH NHÀ XE");

        tbListGaras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên nhà xe", "Đánh giá", "Giấy phép kinh doanh", "Số điện thoại"
            }
        ));
        jScrollPane1.setViewportView(tbListGaras);

        btDelGara.setText("Xòa nhà xe");
        btDelGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelGaraActionPerformed(evt);
            }
        });

        btUpdateGara.setText("Cập nhật thông tin nhà xe");
        btUpdateGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateGaraActionPerformed(evt);
            }
        });

        btViewDetail.setText("Xem chi tiết");
        btViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewDetailActionPerformed(evt);
            }
        });

        ckShowAll.setText("Hiển thị toàn bộ danh sách");
        ckShowAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckShowAllItemStateChanged(evt);
            }
        });

        jLabel2.setText("Tìm kiếm theo tên nhà xe");

        btSearch.setText("Tìm");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txgaraName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDelGara, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btUpdateGara, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckShowAll)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ckShowAll))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txgaraName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdateGara, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelGara, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDelGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelGaraActionPerformed
        if(tbListGaras.getSelectedRow()==-1) return;
        
        
        
        String sql = "UPDATE Gara SET Active='false',Account=NULL WHERE Gara_Name=?";
        String sql2 = "SELECT Account from Gara where Gara_Name=?";
        String sql3 = "DELETE Account where Account=?";
        String garaName = "";
        String account = ""; 
        garaName = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),0);
        
        
        int confirm = JOptionPane.showConfirmDialog(rootPane,"Xác nhận thao tác xóa" ,"Bạn có chắc chắn xóa nhà xe \n"+garaName, JOptionPane.YES_NO_OPTION);
                
        if(confirm ==JOptionPane.NO_OPTION){        
                JOptionPane.showMessageDialog(rootPane, "Thao tác xóa bị hủy");
        }else if(confirm ==JOptionPane.YES_OPTION){
            PreparedStatement pstt;
        try {
            PreparedStatement pstt2 = connection.prepareStatement(sql2);
            pstt2.setString(1, garaName);
            ResultSet rs2 = pstt2.executeQuery(); 
            if(rs2.next()){
                account = rs2.getString(1);
            }
         } catch (SQLException ex) {
                Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        
        
        
            //cap nhat trang thai: active = false, account = NULL
        try {
            pstt = connection.prepareStatement(sql);
            pstt.setString(1, garaName);
            int result = pstt.executeUpdate();
            if(result>0){
                
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowStaffList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        PreparedStatement pstt3;
            try {
                pstt3 = connection.prepareStatement(sql3);
                pstt3.setString(1, account);
                int x= pstt3.executeUpdate();
                if(x>0){
                    JOptionPane.showMessageDialog(rootPane, "Xóa nhà xe thành công!");
                    performed(connection);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_btDelGaraActionPerformed

    private void btUpdateGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateGaraActionPerformed
        if(tbListGaras.getSelectedRow()==-1) return ; 
        
        
        String sql = "select Gara_Picture,Account,Gara_Review from Gara where Gara_Name=?";
        String sql2= "select password from Account where account = ?"; 
        
        
        String garaName = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),0);
        String picture ="";
        String account="";
        String password="";
        
        String review = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),1);
        float garaPoint = 0;
        String BusResNum = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),2);
        String active = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),3);
        String phone =(String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),4);
        PreparedStatement pstt;
        try {
            pstt = connection.prepareStatement(sql);
        pstt.setString(1, garaName);
        ResultSet rs = pstt.executeQuery(); 
        if(rs.next()){
            picture = rs.getString(1);
            account = rs.getString(2);
            garaPoint = rs.getFloat(3);
        }
        } catch (SQLException ex) {
            Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        PreparedStatement pstt2;
        try {
            pstt2 = connection.prepareStatement(sql2);
            pstt2.setString(1, account);
            ResultSet rs = pstt2.executeQuery();
            if(rs.next()){
                password = rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        UpGara upGara = new UpGara(this, rootPaneCheckingEnabled,garaName,picture,review,garaPoint,BusResNum,active,account, password,phone);
        upGara.setLocationRelativeTo(null);
        upGara.setVisible(true);
        performed(connection);
    }//GEN-LAST:event_btUpdateGaraActionPerformed

    private void btViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewDetailActionPerformed
        
        if(tbListGaras.getSelectedRow()==-1) return; 
       
        
        String sql = "select Gara_Picture,Account from Gara where Gara_Name=?";
        String sql2= "select password from Account where account = ?"; 
        
        String garaName = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),0);
        String picture ="";
        String review = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),1);
        String BusResNum = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),2);
        String active = (String) tbListGaras.getValueAt(tbListGaras.getSelectedRow(),3);
        String account=""; 
        String password=""; 
        PreparedStatement pstt;
        try {
            pstt = connection.prepareStatement(sql);
        pstt.setString(1, garaName);
        ResultSet rs = pstt.executeQuery(); 
        if(rs.next()){
            picture = rs.getString(1);
            account = rs.getString(2);
        }
        } catch (SQLException ex) {
            Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        PreparedStatement pstt2;
        try {
            pstt2 = connection.prepareStatement(sql2);
            pstt2.setString(1, account);
            ResultSet rs = pstt2.executeQuery();
            if(rs.next()){
                password = rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        ViewDetailGara viewDetailGara = new ViewDetailGara(this, rootPaneCheckingEnabled,garaName,picture,review,BusResNum,active,account, password);
        viewDetailGara.setLocationRelativeTo(null);
        viewDetailGara.setVisible(true);
    }//GEN-LAST:event_btViewDetailActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
       String garaName = txgaraName.getText();
       garaName = garaName.trim();
       ckShowAll.setSelected(false);
       
      
        performedDueName(connection, garaName);
       
    }//GEN-LAST:event_btSearchActionPerformed

    private void ckShowAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckShowAllItemStateChanged
        if(ckShowAll.isSelected()){
            performed(connection);
        }
    }//GEN-LAST:event_ckShowAllItemStateChanged

    private void ckShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckShowAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckShowAllActionPerformed

    private void txgaraNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txgaraNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txgaraNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGaraList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGaraList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGaraList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGaraList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowGaraList().setVisible(true);
            }
        });
    }
    public void performedActiveGaras(DefaultTableModel dtf, Connection conn){
        String sql = "SELECT * FROM Gara where active = 'True'"; 
        
        
        
        ResultSet rs; 
        try { 
            Statement stt = conn.createStatement();
            rs = stt.executeQuery(sql); 
            while(rs.next()){
            String garaName = rs.getString(1);
            float garaPoint = rs.getFloat(3);
            String phone = rs.getString(7);
            String garaReview=""; 
            if(garaPoint>=1 && garaPoint<2){
                garaReview = "Rất tệ";
            }else if(garaPoint>=2 && garaPoint<3){
                garaReview = "Tệ";
            }else if(garaPoint>=3 && garaPoint<4){
                garaReview = "Tạm ổn";
            }else if(garaPoint>=4 && garaPoint<4.5){
                garaReview = "Tốt";
            }else if(garaPoint>=4.5){
                garaReview = "Tuyệt vời";
            }else if(garaPoint==-1){
                garaReview = "Chưa được đánh giá";
            }
            String Bus_Res_number = rs.getString(4);
            boolean active = rs.getBoolean(5);
            String statement; 
            if(active==true) statement = "Đang hợp tác";
            else statement = "Ngừng hợp tác";
               
            dtf.addRow(new Object[]{garaName,garaReview,Bus_Res_number,statement,phone});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowStaffList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public void performedInActiveGaras(DefaultTableModel dtf,Connection conn){
        String sql = "SELECT * FROM Gara where active = 'False'"; 
        
        ResultSet rs; 
        try { 
            Statement stt = conn.createStatement();
            rs = stt.executeQuery(sql); 
            while(rs.next()){
            String garaName = rs.getString(1);
            float garaPoint = rs.getFloat(3);
            String phone = rs.getString(7);
            String garaReview=""; 
            if(garaPoint>=1 && garaPoint<2){
                garaReview = "Rất tệ";
            }else if(garaPoint>=2 && garaPoint<3){
                garaReview = "Tệ";
            }else if(garaPoint>=3 && garaPoint<4){
                garaReview = "Tạm ổn";
            }else if(garaPoint>=4 && garaPoint<4.5){
                garaReview = "Tốt";
            }else if(garaPoint>=4.5){
                garaReview = "Tuyệt vời";   
            }else if(garaPoint==-1){
                garaReview = "Chưa được đánh giá";   
            }
            String Bus_Res_number = rs.getString(4);
            
            String statement = "Ngừng hợp tác";
            
            
            dtf.addRow(new Object[]{garaName,garaReview,Bus_Res_number,statement,phone});
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowStaffList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public void performed(Connection conn){
        dtf = new DefaultTableModel();
        ListSelectionModel listSelectionModel = tbListGaras.getSelectionModel(); 
        listSelectionModel.setSelectionMode(listSelectionModel.SINGLE_SELECTION);
        tbListGaras.setModel(dtf);
        
        
        dtf.addColumn("Tên nhà xe");
        dtf.addColumn("Đánh giá");
        dtf.addColumn("Giấy phép kinh doanh");
        dtf.addColumn("Trạng thái");
        dtf.addColumn("Số điện thoại");
        performedActiveGaras(dtf, conn);
        performedInActiveGaras(dtf,conn);
    }
    public void performedDueName(Connection conn, String name){
        dtf = new DefaultTableModel();
        ListSelectionModel listSelectionModel = tbListGaras.getSelectionModel(); 
        listSelectionModel.setSelectionMode(listSelectionModel.SINGLE_SELECTION);
        tbListGaras.setModel(dtf);
        
        
        dtf.addColumn("Tên nhà xe");
        dtf.addColumn("Đánh giá");
        dtf.addColumn("Giấy phép kinh doanh");
        dtf.addColumn("Trạng thái");
        String sql = "SELECT * FROM Gara where Gara_Name like N'%"+name+"%'"; 
        
        
        
        ResultSet rs; 
        try { 
            Statement stt = conn.createStatement();
            rs = stt.executeQuery(sql); 
            while(rs.next()){
            String garaName = rs.getString(1);
            float garaPoint = rs.getFloat(3);
            String garaReview=""; 
            if(garaPoint>=1 && garaPoint<2){
                garaReview = "Rất tệ";
            }else if(garaPoint>=2 && garaPoint<3){
                garaReview = "Tệ";
            }else if(garaPoint>=3 && garaPoint<4){
                garaReview = "Tạm ổn";
            }else if(garaPoint>=4 && garaPoint<4.5){
                garaReview = "Tốt";
            }else if(garaPoint>=4.5){
                garaReview = "Tuyệt vời";
            }else if(garaPoint==-1){
                garaReview = "Chưa được đánh giá";
            }
            String Bus_Res_number = rs.getString(4);
            boolean active = rs.getBoolean(5);
            String statement; 
            if(active==true) statement = "Đang hợp tác";
            else statement = "Ngừng hợp tác";
               
            dtf.addRow(new Object[]{garaName,garaReview,Bus_Res_number,statement});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowStaffList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelGara;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUpdateGara;
    private javax.swing.JButton btViewDetail;
    private javax.swing.JCheckBox ckShowAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListGaras;
    private javax.swing.JTextField txgaraName;
    // End of variables declaration//GEN-END:variables
}
