/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author huynh
 */
public class UpGara extends javax.swing.JDialog {

    /**
     * Creates new form AddNewGara
     */
    
    String garaName0=""; 
    String active0=""; 
    String account0=""; 
    String picture0=""; 
    String busResNum0=""; 
    String saveFolder = System.getProperty("user.dir")+"\\galaryPicture\\";
    String nameofPicture ="";
    float garaPoint0 = 0; 
    File file; 
    
    //check infor: 
    int empty = -1; 
    int duplicateGaraName = -2;
    int duplicateAccount = -3; 
    int duplicateBusResNum = -4; 
    public UpGara(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public UpGara(java.awt.Frame parent, boolean modal, String garaName, String picture, String review,float garaPoint, String BusResNum ,String active, String account, String password, String phone) {
        super(parent, modal);
        initComponents();
        showInfor(garaName, picture, review, BusResNum, active,account, password,phone);
        this.garaName0 = garaName; 
        this.active0 = active; 
        if(account!=null) this.account0 = account;
        
        this.picture0 = picture;
        this.busResNum0 = BusResNum;
        nameofPicture = picture; 
        this.garaPoint0 = garaPoint;
        
        txGaraReview.setEditable(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbAppreciate = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txGaraName = new javax.swing.JTextField();
        lbshowPicture = new javax.swing.JLabel();
        txPassword = new javax.swing.JTextField();
        txBusResNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txGaraReview = new javax.swing.JTextField();
        btUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btPickPicture = new javax.swing.JButton();
        txAccount = new javax.swing.JTextField();
        cbStatement = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        cbAppreciate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rất tệ", "Tệ", "Ổn", "Tốt", "Tuyệt vời" }));
        jPanel1.add(cbAppreciate);
        cbAppreciate.setBounds(440, 330, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tên nhà xe");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 230, 140, 30);
        jPanel1.add(txGaraName);
        txGaraName.setBounds(200, 260, 410, 30);

        lbshowPicture.setText("jLabel8");
        jPanel1.add(lbshowPicture);
        lbshowPicture.setBounds(730, 220, 414, 420);

        txPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txPassword);
        txPassword.setBounds(200, 560, 410, 30);
        jPanel1.add(txBusResNum);
        txBusResNum.setBounds(200, 390, 410, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Đánh giá lại");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 300, 150, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Tên đăng nhập");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 470, 260, 20);
        jPanel1.add(txGaraReview);
        txGaraReview.setBounds(200, 330, 180, 30);

        btUpdate.setBackground(new java.awt.Color(5, 87, 169));
        btUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btUpdate.setText("Cập nhật thông tin nhà xe");
        btUpdate.setBorderPainted(false);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btUpdate);
        btUpdate.setBounds(244, 600, 330, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Giấy phép đăng kí kinh doanh");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 364, 280, 20);

        btPickPicture.setBackground(new java.awt.Color(5, 87, 169));
        btPickPicture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPickPicture.setForeground(new java.awt.Color(255, 255, 255));
        btPickPicture.setText("Chọn hình ảnh khác");
        btPickPicture.setBorderPainted(false);
        btPickPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPickPictureActionPerformed(evt);
            }
        });
        jPanel1.add(btPickPicture);
        btPickPicture.setBounds(850, 180, 210, 30);
        jPanel1.add(txAccount);
        txAccount.setBounds(200, 500, 410, 30);

        cbStatement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hợp tác", "Ngừng hợp tác" }));
        cbStatement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStatementItemStateChanged(evt);
            }
        });
        jPanel1.add(cbStatement);
        cbStatement.setBounds(280, 440, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Đánh giá");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 300, 130, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Hình ảnh");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(730, 180, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Trạng thái");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 440, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Mật khẩu");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 534, 260, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/iconTong.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 20, 160, 123);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("THÔNG TIN NHÀ XE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 170, 270, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("SĐT");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(440, 450, 30, 14);
        jPanel1.add(txPhone);
        txPhone.setBounds(480, 440, 130, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/BackGround.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        String garaName = txGaraName.getText(); 
        
        String garaReview = txGaraReview.getText();
        
        float garapoint = cbAppreciate.getSelectedIndex();
        garapoint++; 
        
        String BusResNum = txBusResNum.getText(); 
        String active =(String)cbStatement.getSelectedItem();
        
        String account = txAccount.getText();
        String password = txPassword.getText();
        
        String phone = txPhone.getText();
        String phonePattern = "0[0-9]{9}";
        DatVeXe datvexe = new DatVeXe();
        Connection conn = datvexe.layKetNoi();
        
        int resultCheck = checkInfor(garaName, garaReview, BusResNum, account, password, conn);
        if(resultCheck==empty){
            JOptionPane.showMessageDialog(rootPane, "Thông tin phải được điền đầy đủ");
            return; 
        }
        
        
        else  if(resultCheck==duplicateGaraName){
            JOptionPane.showMessageDialog(rootPane, "Tên nhà xe đã có trong hệ thống \nVui lòng chọn tên nhà xe khác!");
            return; 
        }
        
        
        
        else  if(resultCheck==duplicateAccount){
            JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập đã có trong hệ thống \nVui lòng chọn tên đăng nhập khác!");
            return; 
                }
        
        
        
        else if(resultCheck==duplicateBusResNum){
            JOptionPane.showMessageDialog(rootPane, "Giấy phép ĐKKD đã có trong hệ thống \nVui lòng kiểm tra lại!");
            return; 
        }
        
        if(this.garaPoint0==-1){
             this.garaPoint0 = garapoint;
            
        }else if(phone.length()!=10 || phone.matches(phonePattern)==false){
           JOptionPane.showMessageDialog(rootPane, "Số điện thoại sai định dạng");
            return; 
       }else {
           this.garaPoint0 = (this.garaPoint0 + garapoint)/2;
        }
        
         
       
        //hop tac: 
        if(active.equals("Đang hợp tác")){
            //truoc do lam, bay gio van lam: 
            if(active0.equals(active)){
                
                
                String sql = "update Account set Account.Account =?,Password =? where Account.Account=?";
                try {
                    PreparedStatement pstt = conn.prepareStatement(sql);
                    pstt.setString(1, account);
                    pstt.setString(2, password);
                    pstt.setString(3, this.account0);
                    
                    int x = pstt.executeUpdate();
                    if(x>0){
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String sql2 = "UPDATE Gara SET Gara_Name=?,Gara_Picture=?,Gara_Review=?,Bus_Res_number=?,Phone=? where Gara_Name=?";
                try {
                    PreparedStatement pstt2 = conn.prepareStatement(sql2);
                    pstt2.setString(1, garaName);
                    pstt2.setString(2, nameofPicture);
                    pstt2.setFloat(3, garaPoint0);
                    pstt2.setString(4, BusResNum);
//                    pstt2.setString(5, account);
                    pstt2.setString(5, phone);
                    pstt2.setString(6, garaName0);
                    
                    int x = pstt2.executeUpdate();
                    if(x>0){
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
                        this.dispose();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            
            //truoc do nghi, bay gio lam: 
            else{
                
                String sql = "INSERT INTO ACCOUNT values(?,?,?)";
                PreparedStatement pstt;
                try {
                    pstt = conn.prepareStatement(sql);
                    pstt.setString(1, account);
                    pstt.setString(2, password);
                    pstt.setString(3, "Gara");
                    int x = pstt.executeUpdate();
                    if(x>0){
                        
                    }
                 
                } catch (SQLException ex) {
                    Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
                }
                String sql2 = "UPDATE Gara SET Gara_Name=?,Gara_Picture=?,Gara_Review=?,Bus_Res_number=?,Active=?,Account=?,Phone=? where Gara_Name=?";
                try {
                    PreparedStatement pstt2 = conn.prepareStatement(sql2);
                    pstt2.setString(1, garaName);
                    pstt2.setString(2, nameofPicture);
                    pstt2.setFloat(3, this.garaPoint0);
                    pstt2.setString(4, BusResNum);
                    pstt2.setBoolean(5, true);
                    pstt2.setString(6, account);
                    pstt2.setString(7, phone);
                    pstt2.setString(8, garaName0);
                    int x = pstt2.executeUpdate();
                    if(x>0){
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
                        this.dispose();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        }
        
        //ngung hop tac: 
        else{
            //truoc do nghi, bay gio nghi: 
            if(active0.equals(active)){
                String sql2 = "UPDATE Gara SET Gara_Name=?,Gara_Picture=?,Gara_Review=?,Bus_Res_number=?,Phone=? where Gara_Name=?";
                try {
                    PreparedStatement pstt2 = conn.prepareStatement(sql2);
                    pstt2.setString(1, garaName);
                    pstt2.setString(2, nameofPicture);
                    pstt2.setFloat(3, this.garaPoint0);
                    pstt2.setString(4, BusResNum);
                    pstt2.setString(5, phone);
                    pstt2.setString(6, garaName0);
                    int x = pstt2.executeUpdate();
                    if(x>0){
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
                        this.dispose();
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            
            //truoc do lam, bay gio nghi: 
            else{
                
             String sql = "UPDATE Gara SET Active='false',Account=NULL WHERE Gara_Name=?";
             String sql2 = "DELETE Account where Account=?";
            
             PreparedStatement pstt;
        
          //cap nhat trang thai: active = false, account = NULL
        try {
            pstt = conn.prepareStatement(sql);
            pstt.setString(1, garaName0);
            int result = pstt.executeUpdate();
            if(result>0){
                
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShowStaffList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        PreparedStatement pstt3;
            try {
                pstt3 = conn.prepareStatement(sql2);
                pstt3.setString(1, this.account0);
                int x= pstt3.executeUpdate();
                if(x>0){
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật nhà xe thành công!");
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ShowGaraList.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            }
        }
        
        if(nameofPicture.equals(picture0)==false){
            //save file ra thu muc galaryPicture: 
            //luu file anh ra vung nho
            BufferedImage bImage = null;
            try {

                bImage = ImageIO.read(file);
                ImageIO.write(bImage, "jpg", new File(saveFolder+nameofPicture));
                ImageIO.write(bImage, "png", new File(saveFolder+nameofPicture));
                ImageIO.write(bImage, "jpeg", new File(saveFolder+nameofPicture));
 
         } catch (IOException e) {
               System.out.println("Exception occured :" + e.getMessage());
         }
         System.out.println("Images were written succesfully.");
        }
        
        
        
    }//GEN-LAST:event_btUpdateActionPerformed
    public int checkInfor(String garaName, String garaReview, String busResNum, String account, String password, Connection conn){
        
        
        if(garaName.trim().equals("")|| garaReview.trim().equals("")|| busResNum.trim().equals("")|| account.trim().equals("")||password.trim().equals("")){
            return -1; 
        }
        
        if(this.garaName0.equals(garaName)==false){
            String sql = "select * from Gara where Gara_Name=?";
        try {
            PreparedStatement pstt = conn.prepareStatement(sql);
            pstt.setString(1, garaName);
            ResultSet rs = pstt.executeQuery(); 
            if(rs.next()){
                return -2; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
       if(this.account0.equals(account)==false){
           String sql2 = "select * from account where account.account = ?";
        try {
            
            PreparedStatement pstt2 = conn.prepareStatement(sql2);
            pstt2.setString(1, account);
            ResultSet rs = pstt2.executeQuery(); 
            if(rs.next()){
                System.out.println("thong tin bi trung roi ne!");
                return -3; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        
        if(this.busResNum0.equals(busResNum)==false){
            String sql3 = "select Bus_Res_number from Gara where Bus_Res_number=?";
        try {
            PreparedStatement pstt3 = conn.prepareStatement(sql3);
            pstt3.setString(1, busResNum);
            ResultSet rs = pstt3.executeQuery(); 
            if(rs.next()){
                return -4; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpGara.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        
        return 0;
    }
    
    private void cbStatementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStatementItemStateChanged
        if(cbStatement.getSelectedIndex()==0){
            txAccount.setEditable(true);
            txPassword.setEditable(true);
        }else{
            txAccount.setEditable(false);
            txPassword.setEditable(false);
        }
    }//GEN-LAST:event_cbStatementItemStateChanged

    private void btPickPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPickPictureActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Hình ảnh", "jpg","jpeg","png");
        fileChooser.setFileFilter(extension);
        fileChooser.setMultiSelectionEnabled(false);
        
        int x = fileChooser.showDialog(this, "Chọn ảnh nhà xe");
        if(x==JFileChooser.APPROVE_OPTION){
            file = fileChooser.getSelectedFile();
            ImageIcon icon  = new ImageIcon(file.getAbsolutePath());
            Image image = icon.getImage();
            Image newImage = image.getScaledInstance(410,410, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(newImage);
            lbshowPicture.setIcon(icon);
          //lay ten file
          System.out.println(file.getAbsolutePath());
                
            String finalString = file.getAbsolutePath();
            char s = '\\';
            String result="";
            for(int i =finalString.length()-1;i>=0;i--){
                char compareStr = finalString.charAt(i);
                if(Character.compare(s, compareStr)==0){
                    result = finalString.substring(i+1);
                    break;
                }
            }
            nameofPicture = result; 
            System.out.println("ten cua anh: "+nameofPicture);
            
            
        }
    }//GEN-LAST:event_btPickPictureActionPerformed

    private void txPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPasswordActionPerformed
    public void showInfor(String garaName, String picture, String review, String BusResNum, String active,String account, String password,String phone){
        txGaraName.setText(garaName);
        txGaraReview.setText(review);
        txBusResNum.setText(BusResNum);
        cbStatement.setSelectedItem(active);
        txAccount.setText(account);
        txPassword.setText(password);
        txPhone.setText(phone);
        ImageIcon icon  = new ImageIcon(saveFolder+picture);
            Image image = icon.getImage();
            Image newImage = image.getScaledInstance(540,370, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(newImage);
            lbshowPicture.setIcon(icon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpGara dialog = new UpGara(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPickPicture;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbAppreciate;
    private javax.swing.JComboBox<String> cbStatement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbshowPicture;
    private javax.swing.JTextField txAccount;
    private javax.swing.JTextField txBusResNum;
    private javax.swing.JTextField txGaraName;
    private javax.swing.JTextField txGaraReview;
    private javax.swing.JTextField txPassword;
    private javax.swing.JTextField txPhone;
    // End of variables declaration//GEN-END:variables
}
