/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datvexe;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author huynh
 */
public class ViewDetailGara extends javax.swing.JDialog {

    /**
     * Creates new form AddNewGara
     */
    String saveFolder = System.getProperty("user.dir")+"\\galaryPicture\\";
    public ViewDetailGara(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public ViewDetailGara(java.awt.Frame parent, boolean modal, String garaName, String picture, String review, String BusResNum ,String active, String account, String password) {
        super(parent, modal);
        initComponents();
        showInfor(garaName, picture, review, BusResNum, active,account,  password);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txaccount = new javax.swing.JTextField();
        lbShowPicture = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        cbStatement = new javax.swing.JComboBox<>();
        txPassword = new javax.swing.JTextField();
        txGaraName = new javax.swing.JTextField();
        txBusResNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txGaraReview = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Tên đăng nhập");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 430, 150, 17);

        txaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txaccountActionPerformed(evt);
            }
        });
        jPanel1.add(txaccount);
        txaccount.setBounds(200, 460, 370, 30);

        lbShowPicture.setText("jLabel8");
        jPanel1.add(lbShowPicture);
        lbShowPicture.setBounds(690, 180, 410, 420);

        btExit.setBackground(new java.awt.Color(5, 87, 169));
        btExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("Đóng");
        btExit.setBorderPainted(false);
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jPanel1.add(btExit);
        btExit.setBounds(230, 600, 300, 40);

        cbStatement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hợp tác", "Ngừng hợp tác" }));
        jPanel1.add(cbStatement);
        cbStatement.setBounds(380, 320, 190, 30);
        jPanel1.add(txPassword);
        txPassword.setBounds(200, 530, 370, 30);
        jPanel1.add(txGaraName);
        txGaraName.setBounds(200, 260, 370, 30);
        jPanel1.add(txBusResNum);
        txBusResNum.setBounds(200, 390, 370, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tên nhà xe");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 230, 130, 20);
        jPanel1.add(txGaraReview);
        txGaraReview.setBounds(200, 320, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Mật khẩu");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 500, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Đánh giá");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 300, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Trạng thái");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 300, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Giấy phép đăng kí kinh doanh");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 360, 290, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/iconTong.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 20, 160, 123);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("THÔNG TIN NHÀ XE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 170, 270, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/BackGround.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btExitActionPerformed

    private void txaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txaccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txaccountActionPerformed
    public void showInfor(String garaName, String picture, String review, String BusResNum, String active, String account, String password){
        txGaraName.setText(garaName);
        
        txGaraReview.setText(review);
        txBusResNum.setText(BusResNum);
        cbStatement.setSelectedItem(active);
        txaccount.setText(account);
        txPassword.setText(password);
        
        txGaraName.setEditable(false);
        txGaraReview.setEditable(false);
        txBusResNum.setEditable(false);
        cbStatement.setEditable(false);
        txaccount.setEditable(false);
        txPassword.setEditable(false);
        
            ImageIcon icon  = new ImageIcon(saveFolder+picture);
            Image image = icon.getImage();
            Image newImage = image.getScaledInstance(540,370, java.awt.Image.SCALE_SMOOTH);
            icon = new ImageIcon(newImage);
            lbShowPicture.setIcon(icon);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDetailGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDetailGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDetailGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDetailGara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewDetailGara dialog = new ViewDetailGara(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JComboBox<String> cbStatement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbShowPicture;
    private javax.swing.JTextField txBusResNum;
    private javax.swing.JTextField txGaraName;
    private javax.swing.JTextField txGaraReview;
    private javax.swing.JTextField txPassword;
    private javax.swing.JTextField txaccount;
    // End of variables declaration//GEN-END:variables
}
